/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pqp;

public class BV {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BV(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BV obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PQPJNI.delete_BV(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setR(SWIGTYPE_p_a_3__double value) {
    PQPJNI.BV_R_set(swigCPtr, this, SWIGTYPE_p_a_3__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_3__double getR() {
    long cPtr = PQPJNI.BV_R_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_3__double(cPtr, false);
  }

  public void setFirst_child(int value) {
    PQPJNI.BV_first_child_set(swigCPtr, this, value);
  }

  public int getFirst_child() {
    return PQPJNI.BV_first_child_get(swigCPtr, this);
  }

  public BV() {
    this(PQPJNI.new_BV(), true);
  }

  public int Leaf() {
    return PQPJNI.BV_Leaf(swigCPtr, this);
  }

  public double GetSize() {
    return PQPJNI.BV_GetSize(swigCPtr, this);
  }

  public void FitToTris(SWIGTYPE_p_a_3__double O, Tri tris, int num_tris) {
    PQPJNI.BV_FitToTris(swigCPtr, this, SWIGTYPE_p_a_3__double.getCPtr(O), Tri.getCPtr(tris), tris, num_tris);
  }

}
