/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pqp;

public class BVT {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BVT(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BVT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PQPJNI.delete_BVT(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setD(double value) {
    PQPJNI.BVT_d_set(swigCPtr, this, value);
  }

  public double getD() {
    return PQPJNI.BVT_d_get(swigCPtr, this);
  }

  public void setB1(int value) {
    PQPJNI.BVT_b1_set(swigCPtr, this, value);
  }

  public int getB1() {
    return PQPJNI.BVT_b1_get(swigCPtr, this);
  }

  public void setB2(int value) {
    PQPJNI.BVT_b2_set(swigCPtr, this, value);
  }

  public int getB2() {
    return PQPJNI.BVT_b2_get(swigCPtr, this);
  }

  public void setR(SWIGTYPE_p_a_3__double value) {
    PQPJNI.BVT_R_set(swigCPtr, this, SWIGTYPE_p_a_3__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_3__double getR() {
    long cPtr = PQPJNI.BVT_R_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_3__double(cPtr, false);
  }

  public void setT(SWIGTYPE_p_double value) {
    PQPJNI.BVT_T_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getT() {
    long cPtr = PQPJNI.BVT_T_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setPindex(int value) {
    PQPJNI.BVT_pindex_set(swigCPtr, this, value);
  }

  public int getPindex() {
    return PQPJNI.BVT_pindex_get(swigCPtr, this);
  }

  public BVT() {
    this(PQPJNI.new_BVT(), true);
  }

}
