/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pqp;

public class BVTQ {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BVTQ(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BVTQ obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PQPJNI.delete_BVTQ(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BVTQ(int sz) {
    this(PQPJNI.new_BVTQ(sz), true);
  }

  public int Empty() {
    return PQPJNI.BVTQ_Empty(swigCPtr, this);
  }

  public int GetNumTests() {
    return PQPJNI.BVTQ_GetNumTests(swigCPtr, this);
  }

  public int GetSize() {
    return PQPJNI.BVTQ_GetSize(swigCPtr, this);
  }

  public double MinTest() {
    return PQPJNI.BVTQ_MinTest(swigCPtr, this);
  }

  public BVT ExtractMinTest() {
    return new BVT(PQPJNI.BVTQ_ExtractMinTest(swigCPtr, this), true);
  }

  public void AddTest(BVT arg0) {
    PQPJNI.BVTQ_AddTest(swigCPtr, this, BVT.getCPtr(arg0), arg0);
  }

}
