/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pqp;

public class CollisionPair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CollisionPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CollisionPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PQPJNI.delete_CollisionPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId1(int value) {
    PQPJNI.CollisionPair_id1_set(swigCPtr, this, value);
  }

  public int getId1() {
    return PQPJNI.CollisionPair_id1_get(swigCPtr, this);
  }

  public void setId2(int value) {
    PQPJNI.CollisionPair_id2_set(swigCPtr, this, value);
  }

  public int getId2() {
    return PQPJNI.CollisionPair_id2_get(swigCPtr, this);
  }

  public CollisionPair() {
    this(PQPJNI.new_CollisionPair(), true);
  }

}
