/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pqp;

public class DoubleArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DoubleArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DoubleArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PQPJNI.delete_DoubleArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DoubleArray(int nelements) {
    this(PQPJNI.new_DoubleArray(nelements), true);
  }

  public double getitem(int index) {
    return PQPJNI.DoubleArray_getitem(swigCPtr, this, index);
  }

  public void setitem(int index, double value) {
    PQPJNI.DoubleArray_setitem(swigCPtr, this, index, value);
  }

  public SWIGTYPE_p_double cast() {
    long cPtr = PQPJNI.DoubleArray_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static DoubleArray frompointer(SWIGTYPE_p_double t) {
    long cPtr = PQPJNI.DoubleArray_frompointer(SWIGTYPE_p_double.getCPtr(t));
    return (cPtr == 0) ? null : new DoubleArray(cPtr, false);
  }

}
