/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pqp;

public class PQP implements PQPConstants {
  public static int getPQP_OK() {
    return PQPJNI.PQP_OK_get();
  }

  public static int getPQP_ERR_MODEL_OUT_OF_MEMORY() {
    return PQPJNI.PQP_ERR_MODEL_OUT_OF_MEMORY_get();
  }

  public static int getPQP_ERR_OUT_OF_MEMORY() {
    return PQPJNI.PQP_ERR_OUT_OF_MEMORY_get();
  }

  public static int getPQP_ERR_UNPROCESSED_MODEL() {
    return PQPJNI.PQP_ERR_UNPROCESSED_MODEL_get();
  }

  public static int getPQP_ERR_BUILD_OUT_OF_SEQUENCE() {
    return PQPJNI.PQP_ERR_BUILD_OUT_OF_SEQUENCE_get();
  }

  public static int getPQP_ERR_BUILD_EMPTY_MODEL() {
    return PQPJNI.PQP_ERR_BUILD_EMPTY_MODEL_get();
  }

  public static int getPQP_ALL_CONTACTS() {
    return PQPJNI.PQP_ALL_CONTACTS_get();
  }

  public static int getPQP_FIRST_CONTACT() {
    return PQPJNI.PQP_FIRST_CONTACT_get();
  }

  public static int PQP_Collide(PQP_CollideResult result, SWIGTYPE_p_a_3__double R1, SWIGTYPE_p_double T1, PQP_Model o1, SWIGTYPE_p_a_3__double R2, SWIGTYPE_p_double T2, PQP_Model o2, int flag) {
    return PQPJNI.PQP_Collide__SWIG_0(PQP_CollideResult.getCPtr(result), result, SWIGTYPE_p_a_3__double.getCPtr(R1), SWIGTYPE_p_double.getCPtr(T1), PQP_Model.getCPtr(o1), o1, SWIGTYPE_p_a_3__double.getCPtr(R2), SWIGTYPE_p_double.getCPtr(T2), PQP_Model.getCPtr(o2), o2, flag);
  }

  public static int PQP_Collide(PQP_CollideResult result, SWIGTYPE_p_a_3__double R1, SWIGTYPE_p_double T1, PQP_Model o1, SWIGTYPE_p_a_3__double R2, SWIGTYPE_p_double T2, PQP_Model o2) {
    return PQPJNI.PQP_Collide__SWIG_1(PQP_CollideResult.getCPtr(result), result, SWIGTYPE_p_a_3__double.getCPtr(R1), SWIGTYPE_p_double.getCPtr(T1), PQP_Model.getCPtr(o1), o1, SWIGTYPE_p_a_3__double.getCPtr(R2), SWIGTYPE_p_double.getCPtr(T2), PQP_Model.getCPtr(o2), o2);
  }

  public static int build_model(PQP_Model m) {
    return PQPJNI.build_model(PQP_Model.getCPtr(m), m);
  }

  public static int BV_Overlap(SWIGTYPE_p_a_3__double R, SWIGTYPE_p_double T, BV b1, BV b2) {
    return PQPJNI.BV_Overlap(SWIGTYPE_p_a_3__double.getCPtr(R), SWIGTYPE_p_double.getCPtr(T), BV.getCPtr(b1), b1, BV.getCPtr(b2), b2);
  }

  public static int LChild(int p) {
    return PQPJNI.LChild(p);
  }

  public static int Parent(int c) {
    return PQPJNI.Parent(c);
  }

  public static double GetTime() {
    return PQPJNI.GetTime();
  }

  public static double getM_PI() {
    return PQPJNI.M_PI_get();
  }

  public static void Mprintg(SWIGTYPE_p_a_3__double M) {
    PQPJNI.Mprintg(SWIGTYPE_p_a_3__double.getCPtr(M));
  }

  public static void Mfprint(SWIGTYPE_p_FILE f, SWIGTYPE_p_a_3__double M) {
    PQPJNI.Mfprint(SWIGTYPE_p_FILE.getCPtr(f), SWIGTYPE_p_a_3__double.getCPtr(M));
  }

  public static void Mprint(SWIGTYPE_p_a_3__double M) {
    PQPJNI.Mprint(SWIGTYPE_p_a_3__double.getCPtr(M));
  }

  public static void Vprintg(SWIGTYPE_p_double V) {
    PQPJNI.Vprintg(SWIGTYPE_p_double.getCPtr(V));
  }

  public static void Vfprint(SWIGTYPE_p_FILE f, SWIGTYPE_p_double V) {
    PQPJNI.Vfprint(SWIGTYPE_p_FILE.getCPtr(f), SWIGTYPE_p_double.getCPtr(V));
  }

  public static void Vprint(SWIGTYPE_p_double V) {
    PQPJNI.Vprint(SWIGTYPE_p_double.getCPtr(V));
  }

  public static void Midentity(SWIGTYPE_p_a_3__double M) {
    PQPJNI.Midentity(SWIGTYPE_p_a_3__double.getCPtr(M));
  }

  public static void Videntity(SWIGTYPE_p_double T) {
    PQPJNI.Videntity(SWIGTYPE_p_double.getCPtr(T));
  }

  public static void McM(SWIGTYPE_p_a_3__double Mr, SWIGTYPE_p_a_3__double M) {
    PQPJNI.McM(SWIGTYPE_p_a_3__double.getCPtr(Mr), SWIGTYPE_p_a_3__double.getCPtr(M));
  }

  public static void MTcM(SWIGTYPE_p_a_3__double Mr, SWIGTYPE_p_a_3__double M) {
    PQPJNI.MTcM(SWIGTYPE_p_a_3__double.getCPtr(Mr), SWIGTYPE_p_a_3__double.getCPtr(M));
  }

  public static void VcV(SWIGTYPE_p_double Vr, SWIGTYPE_p_double V) {
    PQPJNI.VcV(SWIGTYPE_p_double.getCPtr(Vr), SWIGTYPE_p_double.getCPtr(V));
  }

  public static void McolcV(SWIGTYPE_p_double Vr, SWIGTYPE_p_a_3__double M, int c) {
    PQPJNI.McolcV(SWIGTYPE_p_double.getCPtr(Vr), SWIGTYPE_p_a_3__double.getCPtr(M), c);
  }

  public static void McolcMcol(SWIGTYPE_p_a_3__double Mr, int cr, SWIGTYPE_p_a_3__double M, int c) {
    PQPJNI.McolcMcol(SWIGTYPE_p_a_3__double.getCPtr(Mr), cr, SWIGTYPE_p_a_3__double.getCPtr(M), c);
  }

  public static void MxMpV(SWIGTYPE_p_a_3__double Mr, SWIGTYPE_p_a_3__double M1, SWIGTYPE_p_a_3__double M2, SWIGTYPE_p_double T) {
    PQPJNI.MxMpV(SWIGTYPE_p_a_3__double.getCPtr(Mr), SWIGTYPE_p_a_3__double.getCPtr(M1), SWIGTYPE_p_a_3__double.getCPtr(M2), SWIGTYPE_p_double.getCPtr(T));
  }

  public static void MxM(SWIGTYPE_p_a_3__double Mr, SWIGTYPE_p_a_3__double M1, SWIGTYPE_p_a_3__double M2) {
    PQPJNI.MxM(SWIGTYPE_p_a_3__double.getCPtr(Mr), SWIGTYPE_p_a_3__double.getCPtr(M1), SWIGTYPE_p_a_3__double.getCPtr(M2));
  }

  public static void MxMT(SWIGTYPE_p_a_3__double Mr, SWIGTYPE_p_a_3__double M1, SWIGTYPE_p_a_3__double M2) {
    PQPJNI.MxMT(SWIGTYPE_p_a_3__double.getCPtr(Mr), SWIGTYPE_p_a_3__double.getCPtr(M1), SWIGTYPE_p_a_3__double.getCPtr(M2));
  }

  public static void MTxM(SWIGTYPE_p_a_3__double Mr, SWIGTYPE_p_a_3__double M1, SWIGTYPE_p_a_3__double M2) {
    PQPJNI.MTxM(SWIGTYPE_p_a_3__double.getCPtr(Mr), SWIGTYPE_p_a_3__double.getCPtr(M1), SWIGTYPE_p_a_3__double.getCPtr(M2));
  }

  public static void MxV(SWIGTYPE_p_double Vr, SWIGTYPE_p_a_3__double M1, SWIGTYPE_p_double V1) {
    PQPJNI.MxV(SWIGTYPE_p_double.getCPtr(Vr), SWIGTYPE_p_a_3__double.getCPtr(M1), SWIGTYPE_p_double.getCPtr(V1));
  }

  public static void MxVpV(SWIGTYPE_p_double Vr, SWIGTYPE_p_a_3__double M1, SWIGTYPE_p_double V1, SWIGTYPE_p_double V2) {
    PQPJNI.MxVpV(SWIGTYPE_p_double.getCPtr(Vr), SWIGTYPE_p_a_3__double.getCPtr(M1), SWIGTYPE_p_double.getCPtr(V1), SWIGTYPE_p_double.getCPtr(V2));
  }

  public static void sMxVpV(SWIGTYPE_p_double Vr, double s1, SWIGTYPE_p_a_3__double M1, SWIGTYPE_p_double V1, SWIGTYPE_p_double V2) {
    PQPJNI.sMxVpV(SWIGTYPE_p_double.getCPtr(Vr), s1, SWIGTYPE_p_a_3__double.getCPtr(M1), SWIGTYPE_p_double.getCPtr(V1), SWIGTYPE_p_double.getCPtr(V2));
  }

  public static void MTxV(SWIGTYPE_p_double Vr, SWIGTYPE_p_a_3__double M1, SWIGTYPE_p_double V1) {
    PQPJNI.MTxV(SWIGTYPE_p_double.getCPtr(Vr), SWIGTYPE_p_a_3__double.getCPtr(M1), SWIGTYPE_p_double.getCPtr(V1));
  }

  public static void sMTxV(SWIGTYPE_p_double Vr, double s1, SWIGTYPE_p_a_3__double M1, SWIGTYPE_p_double V1) {
    PQPJNI.sMTxV(SWIGTYPE_p_double.getCPtr(Vr), s1, SWIGTYPE_p_a_3__double.getCPtr(M1), SWIGTYPE_p_double.getCPtr(V1));
  }

  public static void sMxV(SWIGTYPE_p_double Vr, double s1, SWIGTYPE_p_a_3__double M1, SWIGTYPE_p_double V1) {
    PQPJNI.sMxV(SWIGTYPE_p_double.getCPtr(Vr), s1, SWIGTYPE_p_a_3__double.getCPtr(M1), SWIGTYPE_p_double.getCPtr(V1));
  }

  public static void VmV(SWIGTYPE_p_double Vr, SWIGTYPE_p_double V1, SWIGTYPE_p_double V2) {
    PQPJNI.VmV(SWIGTYPE_p_double.getCPtr(Vr), SWIGTYPE_p_double.getCPtr(V1), SWIGTYPE_p_double.getCPtr(V2));
  }

  public static void VpV(SWIGTYPE_p_double Vr, SWIGTYPE_p_double V1, SWIGTYPE_p_double V2) {
    PQPJNI.VpV(SWIGTYPE_p_double.getCPtr(Vr), SWIGTYPE_p_double.getCPtr(V1), SWIGTYPE_p_double.getCPtr(V2));
  }

  public static void VpVxS(SWIGTYPE_p_double Vr, SWIGTYPE_p_double V1, SWIGTYPE_p_double V2, double s) {
    PQPJNI.VpVxS(SWIGTYPE_p_double.getCPtr(Vr), SWIGTYPE_p_double.getCPtr(V1), SWIGTYPE_p_double.getCPtr(V2), s);
  }

  public static void MskewV(SWIGTYPE_p_a_3__double M, SWIGTYPE_p_double v) {
    PQPJNI.MskewV(SWIGTYPE_p_a_3__double.getCPtr(M), SWIGTYPE_p_double.getCPtr(v));
  }

  public static void VcrossV(SWIGTYPE_p_double Vr, SWIGTYPE_p_double V1, SWIGTYPE_p_double V2) {
    PQPJNI.VcrossV(SWIGTYPE_p_double.getCPtr(Vr), SWIGTYPE_p_double.getCPtr(V1), SWIGTYPE_p_double.getCPtr(V2));
  }

  public static double Vlength(SWIGTYPE_p_double V) {
    return PQPJNI.Vlength(SWIGTYPE_p_double.getCPtr(V));
  }

  public static void Vnormalize(SWIGTYPE_p_double V) {
    PQPJNI.Vnormalize(SWIGTYPE_p_double.getCPtr(V));
  }

  public static double VdotV(SWIGTYPE_p_double V1, SWIGTYPE_p_double V2) {
    return PQPJNI.VdotV(SWIGTYPE_p_double.getCPtr(V1), SWIGTYPE_p_double.getCPtr(V2));
  }

  public static double VdistV2(SWIGTYPE_p_double V1, SWIGTYPE_p_double V2) {
    return PQPJNI.VdistV2(SWIGTYPE_p_double.getCPtr(V1), SWIGTYPE_p_double.getCPtr(V2));
  }

  public static void VxS(SWIGTYPE_p_double Vr, SWIGTYPE_p_double V, double s) {
    PQPJNI.VxS(SWIGTYPE_p_double.getCPtr(Vr), SWIGTYPE_p_double.getCPtr(V), s);
  }

  public static void MRotZ(SWIGTYPE_p_a_3__double Mr, double t) {
    PQPJNI.MRotZ(SWIGTYPE_p_a_3__double.getCPtr(Mr), t);
  }

  public static void MRotX(SWIGTYPE_p_a_3__double Mr, double t) {
    PQPJNI.MRotX(SWIGTYPE_p_a_3__double.getCPtr(Mr), t);
  }

  public static void MRotY(SWIGTYPE_p_a_3__double Mr, double t) {
    PQPJNI.MRotY(SWIGTYPE_p_a_3__double.getCPtr(Mr), t);
  }

  public static void MVtoOGL(SWIGTYPE_p_double oglm, SWIGTYPE_p_a_3__double R, SWIGTYPE_p_double T) {
    PQPJNI.MVtoOGL(SWIGTYPE_p_double.getCPtr(oglm), SWIGTYPE_p_a_3__double.getCPtr(R), SWIGTYPE_p_double.getCPtr(T));
  }

  public static void OGLtoMV(SWIGTYPE_p_a_3__double R, SWIGTYPE_p_double T, SWIGTYPE_p_double oglm) {
    PQPJNI.OGLtoMV(SWIGTYPE_p_a_3__double.getCPtr(R), SWIGTYPE_p_double.getCPtr(T), SWIGTYPE_p_double.getCPtr(oglm));
  }

  public static int getQX() {
    return PQPJNI.QX_get();
  }

  public static int getQY() {
    return PQPJNI.QY_get();
  }

  public static int getQZ() {
    return PQPJNI.QZ_get();
  }

  public static int getQW() {
    return PQPJNI.QW_get();
  }

  public static void MRotQ(SWIGTYPE_p_a_3__double destMatrix, SWIGTYPE_p_double srcQuat) {
    PQPJNI.MRotQ(SWIGTYPE_p_a_3__double.getCPtr(destMatrix), SWIGTYPE_p_double.getCPtr(srcQuat));
  }

  public static void Mqinverse(SWIGTYPE_p_a_3__double Mr, SWIGTYPE_p_a_3__double m) {
    PQPJNI.Mqinverse(SWIGTYPE_p_a_3__double.getCPtr(Mr), SWIGTYPE_p_a_3__double.getCPtr(m));
  }

  public static void Meigen(SWIGTYPE_p_a_3__double vout, SWIGTYPE_p_double dout, SWIGTYPE_p_a_3__double a) {
    PQPJNI.Meigen(SWIGTYPE_p_a_3__double.getCPtr(vout), SWIGTYPE_p_double.getCPtr(dout), SWIGTYPE_p_a_3__double.getCPtr(a));
  }

  public static int obb_disjoint(SWIGTYPE_p_a_3__double B, SWIGTYPE_p_double T, SWIGTYPE_p_double a, SWIGTYPE_p_double b) {
    return PQPJNI.obb_disjoint(SWIGTYPE_p_a_3__double.getCPtr(B), SWIGTYPE_p_double.getCPtr(T), SWIGTYPE_p_double.getCPtr(a), SWIGTYPE_p_double.getCPtr(b));
  }

  public static float sqrt(float x) {
    return PQPJNI.sqrt(x);
  }

  public static float cos(float x) {
    return PQPJNI.cos(x);
  }

  public static float sin(float x) {
    return PQPJNI.sin(x);
  }

  public static float fabs(float x) {
    return PQPJNI.fabs(x);
  }

  public static void ClipToRange(SWIGTYPE_p_double val, double a, double b) {
    PQPJNI.ClipToRange(SWIGTYPE_p_double.getCPtr(val), a, b);
  }

  public static void SegCoords(SWIGTYPE_p_double t, SWIGTYPE_p_double u, double a, double b, double A_dot_B, double A_dot_T, double B_dot_T) {
    PQPJNI.SegCoords(SWIGTYPE_p_double.getCPtr(t), SWIGTYPE_p_double.getCPtr(u), a, b, A_dot_B, A_dot_T, B_dot_T);
  }

  public static int InVoronoi(double a, double b, double Anorm_dot_B, double Anorm_dot_T, double A_dot_B, double A_dot_T, double B_dot_T) {
    return PQPJNI.InVoronoi(a, b, Anorm_dot_B, Anorm_dot_T, A_dot_B, A_dot_T, B_dot_T);
  }

  public static double RectDist(SWIGTYPE_p_a_3__double Rab, SWIGTYPE_p_double Tab, SWIGTYPE_p_double a, SWIGTYPE_p_double b) {
    return PQPJNI.RectDist(SWIGTYPE_p_a_3__double.getCPtr(Rab), SWIGTYPE_p_double.getCPtr(Tab), SWIGTYPE_p_double.getCPtr(a), SWIGTYPE_p_double.getCPtr(b));
  }

  public static double TriDist(SWIGTYPE_p_double p, SWIGTYPE_p_double q, SWIGTYPE_p_a_3__double s, SWIGTYPE_p_a_3__double t) {
    return PQPJNI.TriDist(SWIGTYPE_p_double.getCPtr(p), SWIGTYPE_p_double.getCPtr(q), SWIGTYPE_p_a_3__double.getCPtr(s), SWIGTYPE_p_a_3__double.getCPtr(t));
  }

}
