/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pqp;

public class PQP_Model {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PQP_Model(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PQP_Model obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PQPJNI.delete_PQP_Model(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBuild_state(int value) {
    PQPJNI.PQP_Model_build_state_set(swigCPtr, this, value);
  }

  public int getBuild_state() {
    return PQPJNI.PQP_Model_build_state_get(swigCPtr, this);
  }

  public void setTris(Tri value) {
    PQPJNI.PQP_Model_tris_set(swigCPtr, this, Tri.getCPtr(value), value);
  }

  public Tri getTris() {
    long cPtr = PQPJNI.PQP_Model_tris_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Tri(cPtr, false);
  }

  public void setNum_tris(int value) {
    PQPJNI.PQP_Model_num_tris_set(swigCPtr, this, value);
  }

  public int getNum_tris() {
    return PQPJNI.PQP_Model_num_tris_get(swigCPtr, this);
  }

  public void setNum_tris_alloced(int value) {
    PQPJNI.PQP_Model_num_tris_alloced_set(swigCPtr, this, value);
  }

  public int getNum_tris_alloced() {
    return PQPJNI.PQP_Model_num_tris_alloced_get(swigCPtr, this);
  }

  public void setB(BV value) {
    PQPJNI.PQP_Model_b_set(swigCPtr, this, BV.getCPtr(value), value);
  }

  public BV getB() {
    long cPtr = PQPJNI.PQP_Model_b_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BV(cPtr, false);
  }

  public void setNum_bvs(int value) {
    PQPJNI.PQP_Model_num_bvs_set(swigCPtr, this, value);
  }

  public int getNum_bvs() {
    return PQPJNI.PQP_Model_num_bvs_get(swigCPtr, this);
  }

  public void setNum_bvs_alloced(int value) {
    PQPJNI.PQP_Model_num_bvs_alloced_set(swigCPtr, this, value);
  }

  public int getNum_bvs_alloced() {
    return PQPJNI.PQP_Model_num_bvs_alloced_get(swigCPtr, this);
  }

  public void setLast_tri(Tri value) {
    PQPJNI.PQP_Model_last_tri_set(swigCPtr, this, Tri.getCPtr(value), value);
  }

  public Tri getLast_tri() {
    long cPtr = PQPJNI.PQP_Model_last_tri_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Tri(cPtr, false);
  }

  public BV child(int n) {
    long cPtr = PQPJNI.PQP_Model_child(swigCPtr, this, n);
    return (cPtr == 0) ? null : new BV(cPtr, false);
  }

  public PQP_Model() {
    this(PQPJNI.new_PQP_Model(), true);
  }

  public int BeginModel(int num_tris) {
    return PQPJNI.PQP_Model_BeginModel__SWIG_0(swigCPtr, this, num_tris);
  }

  public int BeginModel() {
    return PQPJNI.PQP_Model_BeginModel__SWIG_1(swigCPtr, this);
  }

  public int AddTri(SWIGTYPE_p_double p1, SWIGTYPE_p_double p2, SWIGTYPE_p_double p3, int id) {
    return PQPJNI.PQP_Model_AddTri(swigCPtr, this, SWIGTYPE_p_double.getCPtr(p1), SWIGTYPE_p_double.getCPtr(p2), SWIGTYPE_p_double.getCPtr(p3), id);
  }

  public int EndModel() {
    return PQPJNI.PQP_Model_EndModel(swigCPtr, this);
  }

  public int MemUsage(int msg) {
    return PQPJNI.PQP_Model_MemUsage(swigCPtr, this, msg);
  }

}
