/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pqp;

public class PQP_ToleranceResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PQP_ToleranceResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PQP_ToleranceResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PQPJNI.delete_PQP_ToleranceResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNum_bv_tests(int value) {
    PQPJNI.PQP_ToleranceResult_num_bv_tests_set(swigCPtr, this, value);
  }

  public int getNum_bv_tests() {
    return PQPJNI.PQP_ToleranceResult_num_bv_tests_get(swigCPtr, this);
  }

  public void setNum_tri_tests(int value) {
    PQPJNI.PQP_ToleranceResult_num_tri_tests_set(swigCPtr, this, value);
  }

  public int getNum_tri_tests() {
    return PQPJNI.PQP_ToleranceResult_num_tri_tests_get(swigCPtr, this);
  }

  public void setQuery_time_secs(double value) {
    PQPJNI.PQP_ToleranceResult_query_time_secs_set(swigCPtr, this, value);
  }

  public double getQuery_time_secs() {
    return PQPJNI.PQP_ToleranceResult_query_time_secs_get(swigCPtr, this);
  }

  public void setR(SWIGTYPE_p_a_3__double value) {
    PQPJNI.PQP_ToleranceResult_R_set(swigCPtr, this, SWIGTYPE_p_a_3__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_3__double getR() {
    long cPtr = PQPJNI.PQP_ToleranceResult_R_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_3__double(cPtr, false);
  }

  public void setT(SWIGTYPE_p_double value) {
    PQPJNI.PQP_ToleranceResult_T_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getT() {
    long cPtr = PQPJNI.PQP_ToleranceResult_T_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setCloser_than_tolerance(int value) {
    PQPJNI.PQP_ToleranceResult_closer_than_tolerance_set(swigCPtr, this, value);
  }

  public int getCloser_than_tolerance() {
    return PQPJNI.PQP_ToleranceResult_closer_than_tolerance_get(swigCPtr, this);
  }

  public void setTolerance(double value) {
    PQPJNI.PQP_ToleranceResult_tolerance_set(swigCPtr, this, value);
  }

  public double getTolerance() {
    return PQPJNI.PQP_ToleranceResult_tolerance_get(swigCPtr, this);
  }

  public void setDistance(double value) {
    PQPJNI.PQP_ToleranceResult_distance_set(swigCPtr, this, value);
  }

  public double getDistance() {
    return PQPJNI.PQP_ToleranceResult_distance_get(swigCPtr, this);
  }

  public void setP1(SWIGTYPE_p_double value) {
    PQPJNI.PQP_ToleranceResult_p1_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getP1() {
    long cPtr = PQPJNI.PQP_ToleranceResult_p1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setP2(SWIGTYPE_p_double value) {
    PQPJNI.PQP_ToleranceResult_p2_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getP2() {
    long cPtr = PQPJNI.PQP_ToleranceResult_p2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setQsize(int value) {
    PQPJNI.PQP_ToleranceResult_qsize_set(swigCPtr, this, value);
  }

  public int getQsize() {
    return PQPJNI.PQP_ToleranceResult_qsize_get(swigCPtr, this);
  }

  public int NumBVTests() {
    return PQPJNI.PQP_ToleranceResult_NumBVTests(swigCPtr, this);
  }

  public int NumTriTests() {
    return PQPJNI.PQP_ToleranceResult_NumTriTests(swigCPtr, this);
  }

  public double QueryTimeSecs() {
    return PQPJNI.PQP_ToleranceResult_QueryTimeSecs(swigCPtr, this);
  }

  public double Distance() {
    return PQPJNI.PQP_ToleranceResult_Distance(swigCPtr, this);
  }

  public SWIGTYPE_p_double P1() {
    long cPtr = PQPJNI.PQP_ToleranceResult_P1(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public SWIGTYPE_p_double P2() {
    long cPtr = PQPJNI.PQP_ToleranceResult_P2(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public int CloserThanTolerance() {
    return PQPJNI.PQP_ToleranceResult_CloserThanTolerance(swigCPtr, this);
  }

  public PQP_ToleranceResult() {
    this(PQPJNI.new_PQP_ToleranceResult(), true);
  }

}
