/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pqp;

public class PQP_CollideResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PQP_CollideResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PQP_CollideResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PQPJNI.delete_PQP_CollideResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNum_bv_tests(int value) {
    PQPJNI.PQP_CollideResult_num_bv_tests_set(swigCPtr, this, value);
  }

  public int getNum_bv_tests() {
    return PQPJNI.PQP_CollideResult_num_bv_tests_get(swigCPtr, this);
  }

  public void setNum_tri_tests(int value) {
    PQPJNI.PQP_CollideResult_num_tri_tests_set(swigCPtr, this, value);
  }

  public int getNum_tri_tests() {
    return PQPJNI.PQP_CollideResult_num_tri_tests_get(swigCPtr, this);
  }

  public void setQuery_time_secs(double value) {
    PQPJNI.PQP_CollideResult_query_time_secs_set(swigCPtr, this, value);
  }

  public double getQuery_time_secs() {
    return PQPJNI.PQP_CollideResult_query_time_secs_get(swigCPtr, this);
  }

  public void setR(SWIGTYPE_p_a_3__double value) {
    PQPJNI.PQP_CollideResult_R_set(swigCPtr, this, SWIGTYPE_p_a_3__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_3__double getR() {
    long cPtr = PQPJNI.PQP_CollideResult_R_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_3__double(cPtr, false);
  }

  public void setT(SWIGTYPE_p_double value) {
    PQPJNI.PQP_CollideResult_T_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getT() {
    long cPtr = PQPJNI.PQP_CollideResult_T_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setNum_pairs_alloced(int value) {
    PQPJNI.PQP_CollideResult_num_pairs_alloced_set(swigCPtr, this, value);
  }

  public int getNum_pairs_alloced() {
    return PQPJNI.PQP_CollideResult_num_pairs_alloced_get(swigCPtr, this);
  }

  public void setNum_pairs(int value) {
    PQPJNI.PQP_CollideResult_num_pairs_set(swigCPtr, this, value);
  }

  public int getNum_pairs() {
    return PQPJNI.PQP_CollideResult_num_pairs_get(swigCPtr, this);
  }

  public void setPairs(CollisionPair value) {
    PQPJNI.PQP_CollideResult_pairs_set(swigCPtr, this, CollisionPair.getCPtr(value), value);
  }

  public CollisionPair getPairs() {
    long cPtr = PQPJNI.PQP_CollideResult_pairs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CollisionPair(cPtr, false);
  }

  public void SizeTo(int n) {
    PQPJNI.PQP_CollideResult_SizeTo(swigCPtr, this, n);
  }

  public void Add(int i1, int i2) {
    PQPJNI.PQP_CollideResult_Add(swigCPtr, this, i1, i2);
  }

  public PQP_CollideResult() {
    this(PQPJNI.new_PQP_CollideResult(), true);
  }

  public int NumBVTests() {
    return PQPJNI.PQP_CollideResult_NumBVTests(swigCPtr, this);
  }

  public int NumTriTests() {
    return PQPJNI.PQP_CollideResult_NumTriTests(swigCPtr, this);
  }

  public double QueryTimeSecs() {
    return PQPJNI.PQP_CollideResult_QueryTimeSecs(swigCPtr, this);
  }

  public void FreePairsList() {
    PQPJNI.PQP_CollideResult_FreePairsList(swigCPtr, this);
  }

  public int Colliding() {
    return PQPJNI.PQP_CollideResult_Colliding(swigCPtr, this);
  }

  public int NumPairs() {
    return PQPJNI.PQP_CollideResult_NumPairs(swigCPtr, this);
  }

  public int Id1(int k) {
    return PQPJNI.PQP_CollideResult_Id1(swigCPtr, this, k);
  }

  public int Id2(int k) {
    return PQPJNI.PQP_CollideResult_Id2(swigCPtr, this, k);
  }

}
