/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pqp;

public interface PQPConstants {
  public final static int RSS_TYPE = PQPJNI.RSS_TYPE_get();
  public final static int OBB_TYPE = PQPJNI.OBB_TYPE_get();
  public final static int PQP_BV_TYPE = PQPJNI.PQP_BV_TYPE_get();
}
