/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pqp;

public class Tri {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Tri(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Tri obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PQPJNI.delete_Tri(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setP1(SWIGTYPE_p_double value) {
    PQPJNI.Tri_p1_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getP1() {
    long cPtr = PQPJNI.Tri_p1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setP2(SWIGTYPE_p_double value) {
    PQPJNI.Tri_p2_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getP2() {
    long cPtr = PQPJNI.Tri_p2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setP3(SWIGTYPE_p_double value) {
    PQPJNI.Tri_p3_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getP3() {
    long cPtr = PQPJNI.Tri_p3_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setId(int value) {
    PQPJNI.Tri_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return PQPJNI.Tri_id_get(swigCPtr, this);
  }

  public Tri() {
    this(PQPJNI.new_Tri(), true);
  }

}
